# ESTE CIDIGO IMPRIME LOS NUMEROS
#DEL U1 AL 10
for n in range(1,11):
    print(n)



##crear un programa que me imprima las cinco vocales 

vocales:str="aeiou"
for n in range(0,5):
 print(vocales [n])

 ##crear un programa que me muestre los 8 primos pares 
 for n in range( 1,17 ):
    if n%2==0:
     contador+:1
    print:(f"(n)EL NUMERO(contador)")
  


#crear al programa que pida al usuario escribir una oracion 
#y muestrre por terminalla cantidad de valores a que tiene esa oracion 
#OJO SOLO LAS "a" MINUSCULA
oracion:=str=input("escrube una oracion: ")
contador:int=0
for n in range(0,1en(oracion)):
  if oracion[n]=="a":
    contador=contador+1
    #contador+=1
for n in "aeiou":
   print(n)

for indica,letra in enumerate("aeiou"):
  print(f "el indice es [1] y la letra es (1)")

print(f"la cantidad de letras a que tengo es (contador) ")

# crear un programa que me cuente la cantidad de comas y mem uestre 
#sus indices
#ojo:tiene que pedir al ususario 

frase=input("ingrese una frace:")
contador=0
indice=[n]
for indice,caracter in enumerate(frase):
  if caracter==',':
    contador+=1
